### ISSUE TITLE
When 2 replica set for nifi kop only one nifikop pod serving request(i.e. no load balancer working).

### ISSUE THREAD

**Issue by narayanbhawar10** [konpyutaika/nifikop#235]
### What steps will reproduce the bug?

Increase nifikop replica to reproduce issue.

### What is the expected behavior?

Both replica should work in parallel

### What do you see instead?

Only one replica working

### NiFiKop version

v1.0.0

### Golang version

latest

### Kubernetes version

latest

**Comment by mh013370** [comment]
Are you saying that if you increase a nifikop deployment to 2 replicas, only one actually does any work?

If so, this is by design. This works through [leader election](https://kubernetes.io/docs/concepts/architecture/leases/#leader-election), ensuring there aren't concurrency issues processing individual CRDs in Kubernetes. Given a nifikop deployment with 2 replicas and if/when one nifikop crashes, the other will immediately take over responsibility for all work because it will become the leader. 

This is how all operators work in Kubernetes or any workload that needs to avoid multiple instances processing a single shared resource 🙂

**Comment by narayanbhawar10** [comment]
@mh013370 Thanks for making me understand and I understood. I really appreciate.

**Comment by narayanbhawar10** [comment]
Answered
