### ISSUE TITLE
Controller service getting invalid in other nifi cluster 

### ISSUE THREAD

**Issue by narayanbhawar10** [konpyutaika/nifikop#237]
### What steps will reproduce the bug?

step 1 :-Design data flow and DBCP controller service 
Step 2 :- Save it to registry
Step 3 :- Deploy that flow to new nifi cluster (Where controller service used in data flow is getting invalid)

### What is the expected behavior?

Controller service should be migrated or created as it is on new cluster so that processor's will not be in invalid state. 

### What do you see instead?

Controller service is not migrated or created as it is on new cluster and the  processor's is in invalid state. 

### NiFiKop version

v1.0.0

### Golang version

latest

### Kubernetes version

latest

### NiFi version

1.17.0

**Comment by juldrixx** [comment]
Hello,

The operator does not handle the creation of controller services.
If I'm guessing your problem correctly, you have versioned a dataflow in a NiFi Registry that uses a controller service that is at a higher level. So when you deploy your dataflow to another NiFi cluster, it can't find it.

The operator can't help for that right now because as I said it does not handle the creation of controller services.
So you have two options: 
- include your controller service in the scope of your dataflow not in a higher level
- create manually your controller service in the new cluster at the same level that in the other one and deploy your dataflow

**Comment by narayanbhawar10** [comment]
Understood now .Thanks you for  response and making it easy to understand.
