### ISSUE TITLE
I want to make changes in login-identity-providers.xml as I want to run nifi cluster with single-user-credentials.

### ISSUE THREAD

**Issue by narayanbhawar10** [konpyutaika/nifikop#246]
### Type of question

General Context

### Support question

I want to make changes in login-identity-providers.xml and want to run nifi cluster with single-user-credentials.So Is there any way to update login-identity-providers.xml or run nificluster with single-user-credentials.

**Comment by pranavarnav2** [comment]
Single-user is required by us as well. This is enabled by changing nifi.properties file and running a command on NiFi start (`./bin/nifi.sh set-single-user-credentials USERNAME PASSWORD`). Since running a custom boot command isn't supported by NiFiKop, this isn't possible. If you can add a built-in option to enable single-user by a single setting in `NifiCluster`, that would be great.

**Comment by juldrixx** [comment]
Resolved by https://github.com/konpyutaika/nifikop/pull/278
